### ISSUE TITLE
Bug with Google Home

### ISSUE THREAD

**Issue by domenicoblanco** [kservices/gBridge#10]
Hi, I'm having an issue with Google Home app. When I click on the device I'm unable to change the state of my device and it says that's offline. If I click On or Off in the Home (without clicking on the device) it works fine.
Thanks!
![photo_2018-10-22_15-20-46](https://user-images.githubusercontent.com/9018104/47294678-10877880-d60e-11e8-86f3-4fe5fe88fe2d.jpg)

**Comment by peterkappelt** [comment]
Please try to publish something to the device's status topic (e.g. by sending "1" to gBridge/uxx/dyy/onoff/set).

Reopen the Google Home app afterwards. Is the device still marked as offline?

Have a good one!

**Comment by domenicoblanco** [comment]
Yup, I already publish every update on the status topic and I noticed that this only happens on iOS... Could it be a bug only with the Google Home app?

**Comment by domenicoblanco** [comment]
I received an update of Google Home and now it works fine
