### ISSUE TITLE
gBridge and Tasmota: an internal "babel fish" would be nice

### ISSUE THREAD

**Issue by treepleks** [kservices/gBridge#11]
Dear Peter,

I'm trying to control my tasmota (firmware for ESP8266 based wifi switch sold by Sonoff) devices using gBridge but there is a topic issue. Tasmota has some flexibility in choosing the topics that are used to receive commands and send status but for a switch, setting it on requires a topic that ends with a /Power 1 (or On) as in:
gBridge/u2/mysonoff-light/cmnd/Power 1

while the device will send its status with:
gBridge/u2/mysonoff-light/stat/Power 1

(cmnd and stat can be changed to something else but not the fact that "Power" is last).

It would be great if, instead of having to rely on a local babelfish (as http://va.nce.me/Google_Home_light_control_via_mqtt.html), we could have even more control on the topic that gBridge uses and listens too.

Ok for an imposed prefix with gBridge/<user-id> which , Ican imagine, is required for rerouting.

But would it be possible to control the suffix for sending commands and for receiving status. One could imagine this could be written as

gBridge/userid/%dev/%cmd 

and

gBridge/userid/%dev/%stat

where the strings 
%dev = place where the device name will be inserted
%cmd = string for sending a command to the device
%stat = string that the device uses for reporting status

currently 
%cmd = onoff 
%stat = onoff/stat

but I would be happy to set instead

%cmd = cmnd/Power
%stat = stat/Power

One could even consider that the string for ON/OFF could be customized.

These are just suggestions, of course, the python babelfish of http://va.nce.me/Google_Home_light_control_via_mqtt.html should work but it would be so good to avoid the extra software component :-)

Keep up the good job!

Kind regards
T. Reepleks

**Comment by treepleks** [comment]
This seems feasible by changing the topic. Didn't realize that. Closing.

**Comment by peterkappelt** [comment]
Hi,

sorry - the documentation wasn't up-to-date yet and the feature of changing MQTT topics is a bit hidden at the moment. It'll get better soon.
