### ISSUE TITLE
Missing mysql migration steps on synology MariaDB server

### ISSUE THREAD

**Issue by AlbertDijksma** [kservices/gBridge#16]
Hi Kappelt,

Have done a new installation on my sysnology.
The Scene and Thermostat are not in the database.

xxxx@nas:/volume1/docker/gbridge$ sudo docker-compose exec web php artisan migrate
Password:
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migration table created successfully.
Enter your E-Mail address: xxxx@gmail.com
A new user with the mail "xxxx@gmail.com" and the password "123456" has been created.
Please change the password immediately!

Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_05_21_221047_create_device_type_table
Migrated:  2018_05_21_221047_create_device_type_table
Migrating: 2018_05_21_221542_create_trait_type_table
Migrated:  2018_05_21_221542_create_trait_type_table
Migrating: 2018_05_21_221801_create_device_table
Migrated:  2018_05_21_221801_create_device_table
Migrating: 2018_05_21_222234_create_trait_table
Migrated:  2018_05_21_222234_create_trait_table
Migrating: 2018_05_21_222514_create_google_accesskey_table
Migrated:  2018_05_21_222514_create_google_accesskey_table
Migrating: 2018_06_23_124841_seed_device_type_table
Migrated:  2018_06_23_124841_seed_device_type_table
Migrating: 2018_06_23_125533_seed_trait_type_table
Migrated:  2018_06_23_125533_seed_trait_type_table
Migrating: 2018_06_23_130524_create_first_user
Migrated:  2018_06_23_130524_create_first_user
Migrating: 2018_09_22_125215_fix_foreign_ondelete
Migrated:  2018_09_22_125215_fix_foreign_ondelete
Migrating: 2018_09_22_130425_add_user_name_column
Migrated:  2018_09_22_130425_add_user_name_column
Migrating: 2018_09_22_131146_add_user_language_column
Migrated:  2018_09_22_131146_add_user_language_column
Migrating: 2018_09_24_125634_add_mqtt_topic_column
Migrated:  2018_09_24_125634_add_mqtt_topic_column

**Comment by peterkappelt** [comment]
Hi,
the docker images are not up-to-date yet. For some reason, the build in Travis CI keeps on failing (https://travis-ci.org/kservices/gBridge-docker). I couldn't investigate this problem fully.

Best regards,
Peter

**Comment by AlbertDijksma** [comment]
Hi Peter,
Is working now after removing the old containers
Case can be closed
