### ISSUE TITLE
Self hosted docker instance Accesskey is expired when I create it

### ISSUE THREAD

**Issue by Hypnos3** [kservices/gBridge#18]
If I create a accesskey the key is already expired.

The Valid until timestamp is the timestamp of pushing the add accesskey button.

**Comment by peterkappelt** [comment]
Duplicate of #4. 
Should be fixed with the current release. Are you using the newest version of the Docker containers?

**Comment by Hypnos3** [comment]
I have installed yesterday.
How to update the docker container or need to reinstall?

**Comment by peterkappelt** [comment]
Sorry for answering late.
Try the following procedure for update:
```
docker-compose stop
docker-compose pull web
docker-compose pull redis-worker
docker-compose up
```
