### ISSUE TITLE
Invalid client ID

### ISSUE THREAD

**Issue by samuelebistoletti** [kservices/gBridge#19]
Hi,
I get this message while trying to link my account with the linking function. Client ID is correct, I checked this 3 times.

An error occured
The request by Google Home was malformed. Please try again in a few minute. If this problem persists, please contact the team of Kappelt gBridge. Invalid Client ID has been provided!

Do you have any idea?
Thanks

**Comment by peterkappelt** [comment]
Check the URL of the authentication page. What parameters are given there? Does the parameter `client_id` match your set client id?

**Comment by peterkappelt** [comment]
Please reopen if the issue persists.
