### ISSUE TITLE
[feature request] Add color trait to lights

### ISSUE THREAD

**Issue by Silver-Void** [kservices/gBridge#22]
I have an IR controlled LED lamp and I made an esp8266 change the brightness and turn it on and off through gBridge but I'd also like to take advantage of it's different colors.

**Comment by peterkappelt** [comment]
This topic is discussed in #2. 
Device types and traits will be added step by step. This will happen in the order that users wished in the gBridge user survey. If you've registered for the hosted gBridge service, you've either already received a link to that survey or you are going to receive it within the next days.
However, next features to come are air conditioners and fans. Color won't be supported before late january/ early february.
