### ISSUE TITLE
Scene does not appear in GH

### ISSUE THREAD

**Issue by marquel** [kservices/gBridge#23]
When I create a new device it will appear in GH after syncing, but when I create an scene it does not appear. This way it is impossible to assign the scene to a room, or to activate it manually. However the scene is available in GH with voice command.

I'm using the hosted gBridge.

**Comment by peterkappelt** [comment]
Yeah, unfortunately it is a bug (or a feature?!) of the Google Home app.

Scenes are not shown in the regular device lists. So far, I only know of two places where you can see them:
* Google Home App -> Account (bottom right button) -> Einstellungen ("Settings") -> Tab "Assistant" -> Smart-Home-Steuerung (in the German version)
* When triggering a scene via a routine, in the routine editor dialogs

**Comment by peterkappelt** [comment]
I suppose this feature hasn't been implemented in the GH app, since only few smart home providers even support it.

**Comment by marquel** [comment]
Thanks! I found it in the app and from there it is possible to assingn the scenes to a room.
I tought Itead used scenes in their eWeLink app to control sonoff, but they just emulate a on / off switch :-(
