### ISSUE TITLE
send update notification to GH

### ISSUE THREAD

**Issue by marquel** [kservices/gBridge#24]
I don't know if this an option in google, but at this moment the status in the GH app is only updated when the device is opened. This status does not change anymore, even when the staus is changed. Is it possible to send an update notification to inform the app that the status is changed?

**Comment by peterkappelt** [comment]
Short answer: no. 😁 

There is no documented feature for this purpose, neither in the public documentation nor in documents I've received from Google while publishing this app.

I think, they'll going to add this feature at some point, but the ability to control smart home devices in the app is quite new. I'm regularly sending feature requests to a contact from the Google developer team, I'll add this point in the next mail.

By the way: has anyone ever seen this behavior for other smart home providers (e.g. Hue/ Lightify)?

**Comment by marquel** [comment]
Thanks!
Checked with a sonoff and it's not working as well.
