### ISSUE TITLE
It is no possible to edit Topics and Settings

### ISSUE THREAD

**Issue by AlbertDijksma** [kservices/gBridge#25]
It is no possible to edit Topics and Settings after I add a device
The web site reacts with “Whoops, looks like something went wrong.”

I’m running the latest version in Docker.

**Comment by peterkappelt** [comment]
Try setting the environment variables `APP_ENV` to `local` and `APP_DEBUG` to `'true'` (in your docker compose file). Restart the app afterwards.

The web app will show additional information about the error then.

**Comment by AlbertDijksma** [comment]
ReflectionException thrown with message "Class App\Http\Controllers\Device does not exist"

Stacktrace:
#53 ReflectionException in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:25
#52 ReflectionParameter:getClass in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:25
#51 Illuminate\Routing\RouteSignatureParameters:Illuminate\Routing\{closure} in [internal]:0
#50 array_filter in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:26
#49 Illuminate\Routing\RouteSignatureParameters:fromAction in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php:434
#48 Illuminate\Routing\Route:signatureParameters in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ImplicitRouteBinding.php:22
#47 Illuminate\Routing\ImplicitRouteBinding:resolveForRoute in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:759
#46 Illuminate\Routing\Router:substituteImplicitBindings in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:39
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#42 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:68
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#24 Illuminate\Pipeline\Pipeline:then in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
#23 Illuminate\Routing\Router:runRouteWithinStack in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
#22 Illuminate\Routing\Router:runRoute in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
#21 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
#20 Illuminate\Routing\Router:dispatch in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php:56
#17 Fideloper\Proxy\TrustProxies:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/html/public/index.php:55

**Comment by peterkappelt** [comment]
Well, that's rather strange.

To be hones: I don't have any idea where this could come frome. The error messages doesn't give much information either.

Did it work once before? Are you using the most recent version of the docker images?

Try running `sudo docker-compose exec web php artisan up`

**Comment by peterkappelt** [comment]
Try using the newest docker images, too.

**Comment by jghaanstra** [comment]
Editing the topics and settings is now possible. However, the same issue now occurs when trying to edit `Google Confirmation Type` or `Google Confirmation Pin`.

**Comment by AlbertDijksma** [comment]
Editing the topics and settings is working now after update.
Case can be closed.
Thanks for the quick fix.

**Comment by peterkappelt** [comment]
@jghaanstra Don't forget to update the database structure after the update, by running `docker-compose exec web php artisan migrate`

**Comment by Electronics** [comment]
I've just updated to the latest, and again am getting the following on Edit Topics and Settings:

```
[2019-02-05 15:36:28] production.ERROR: Class App\Http\Controllers\Device does not exist {"userId":1,"email":"lauriekirkcaldy@gmail.com","exception":"[object] (ReflectionException(code: 0): Class App\\Http\\Controllers\\Device does not exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteSignatureParameters.php:25)
[stacktrace]
```

Everything is up to date as far as I can tell:

```
Pulling cache (redis:4)...
4: Pulling from library/redis
Digest: sha256:b16c2623b557d300199014a53754d697c8f92f6e4e062923c26890fcf72a05e5
Status: Image is up to date for redis:4
Pulling redis-worker (pkap/gbridge-redis-worker:latest)...
latest: Pulling from pkap/gbridge-redis-worker
Digest: sha256:e60ff4bf703ffa66694e377f8bcec7eefca98a42cac51663b80272e005b44ea3
Status: Image is up to date for pkap/gbridge-redis-worker:latest
Pulling database (mysql:5)...
5: Pulling from library/mysql
Digest: sha256:1590f2540fd87e39605686873fb10206da4cbd7e83df2bc4110abe9fb740699e
Status: Image is up to date for mysql:5
Pulling web (pkap/gbridge-web:latest)...
latest: Pulling from pkap/gbridge-web
Digest: sha256:7f7569ff2369986bc05c62d08c47b48d0a13ee7c8d07ae0fb8b2544620b43c41
Status: Image is up to date for pkap/gbridge-web:latest
```
