### ISSUE TITLE
Confirming linking does not work on self hosted

### ISSUE THREAD

**Issue by matfiz** [kservices/gBridge#26]
Awesome work with gBridge! 
I have configured gBridge as described in the self-hosted section. I got stuck at account linking. When I navigate to https://my-url/gbridge/gapi/auth and click **Confirm linking**, I am getting error message: *The request by Google Home was malformed. Please try again in a few minute. If this problem persists, please contact the team of Kappelt gBridge. Invalid Client ID has been provided!* 

How should I complete account linking in self-hosted scenario? Should I trigger account linking somewhere from Google Actions Console?

**Comment by peterkappelt** [comment]
Hi,

just to clarify it: You should set up a new project on the https://console.actions.google.com, this should appear as a smarthome provider in your Google Home app, just like the hosted gBridge. You could link your account then there.

There is no need to manually navigate to that URL. The part in the documentation that is about navigating manually to that url is just for the sole purpose of making sure that your webserver works correctly.

**Comment by matfiz** [comment]
Ah, of course! Thank you, @peterkappelt! Can I prepare a PR for the docs somewhere to add this info for the community? 

Closing this

**Comment by peterkappelt** [comment]
Yeah, sure, PR are appreciated.

However, i've actually thought this point is clear 😕 :
> Your gBridge instance should now work a treat!. You can continue with logging in in your Google Home account, have a look at the getting started chapter.

(https://doc.gbridge.io/selfHosted/hostItYourself.html#congratulations)

But sure, why not
