### ISSUE TITLE
Self hosted setup with dockerfiles - Time Error Token

### ISSUE THREAD

**Issue by Merphun** [kservices/gBridge#4]
The access tokens generated had a time stamp of 1 hour ago and were therefore not usable and instantly too old as you set the token validity to 1 hour. My guess is that it is some time zone (maybe summer/winter) bug. 

I solved it by increasing the time to 2 hours in the according php of the docker app

**Comment by peterkappelt** [comment]
This problem will be obselete with the next update (coming at the end of November).
Users will be able to use their account's password for account linking.

**Comment by peterkappelt** [comment]
This issue doesn't persist anymore from now on, since the Accesskey mechanism was dumped.
