### ISSUE TITLE
Turn this service into an open-source community project

### ISSUE THREAD

**Issue by DoganM95** [kservices/gBridge#47]
The project seems to be forgotten and unmaintained. Thus, i suggest turning this project into a open-source project, which will be maintained by a whole community instead of only two persons putting extreme efforts into it. I bet it was a lot of work to get to this point and it should not be a burden you have to carry alone.

The compensation of the costs to keep the servers alive has a lot of room to be discussed.
But please don't let this project die, because it is a hidden gem. By having a whole community maintaining it, it will be up to date and get lots of new functionality, which no one knew they needed.
All commits should run trough a pipeline to achieve a continuous delivery including unit tests to make sure, no one messes up. commits should be reviewed by @peterkappelt to make sure, no one is trying to inject malicious code and make own profits. 

But the domain name and product name should not change, to honor the creator of this project.

**Comment by Chrischi-** [comment]
This thing WAS and IS open-source. Do a fork and host the service. Voila!

**Comment by ghost** [comment]
> This thing WAS and IS open-source. Do a fork and host the service. Voila!

The problem is that the codebase is not what is actually deployed on gbridge.kappelt.net.
See issue https://github.com/kservices/gBridge/issues/42.

**Comment by Chrischi-** [comment]
Should be no problem to program the missing features again.
From then on you have your own codebase.

Whoever does not want to have these constant failures lately, will probably have to go this way.
