### ISSUE TITLE
Sef hosted Setup with Docker - MariaDB on Synology

### ISSUE THREAD

**Issue by Merphun** [kservices/gBridge#5]
I was not able to use my existing MariaDB 10.0 DB on synology as the step:
`docker-compose exec web php artisan migrate`
throw an error:

`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table users add unique users_email_unique(email))`

This error (and the solution by changing some code) is descibed here:
https://laravel-news.com/laravel-5-4-key-too-long-error

I solved it by using another MariaDB 10.2 Dockerfile as MariaDB 10.2 supports this already. Maybe update the docs in order to have people using 10.2+ or edit the code

br
Mike

**Comment by peterkappelt** [comment]
OK, going to fix it in the Next update. Thanks for the tip!

**Comment by peterkappelt** [comment]
Sorry, I've forgotten this issue...

The fix is implemented now.
