### ISSUE TITLE
Connecting MQTT to iobroker (or other smarthome hub)

### ISSUE THREAD

**Issue by Merphun** [kservices/gBridge#6]
Working like a charm BUT it would make things much easier if there would be an option to enter a customizable objectID (the ID from the corresponding smarthome hub) per gbroker device.

Currently I have to link each device by its own because no recognized smarthome hub device name is given

br
Mike

**Comment by blackrozes** [comment]
@Merphun I wrote a quick and dirty script to connect ioBroker states with gBridge https://github.com/blackrozes/ioBrokerScripts/blob/master/gbridge.js. Perhaps that helps.

**Comment by Merphun** [comment]
Hello,
thank you. It works like a charm!

br
Mike

**Comment by peterkappelt** [comment]
Hi,

since the last update of gBridge, you can now assign own MQTT topics per device!

**Comment by Merphun** [comment]
Hi,
if you could point me in the right direction regarding updating gbridge without loosing all my settings (I use your docker composer files) I will happily test it
br
Mike

**Comment by peterkappelt** [comment]
To be honest, I didn't really think about updating docker containers until now...

It should work the following way by only updating the gBridge containers. Your data is stored in the database, it should not be touched by these commands.

To be safe, back up your database first:
```
sudo docker-compose exec database /usr/bin/mysqldump -u gbridge_db --databases gbridge_db -p
```
Enter the MYSQL_PASSWORD from the compose file once prompted. Save the output of this command, so your data could be restored in the case of a serious problem.

Start the upgrade. 
Prefix each command with "docker-compose"
```
stop
pull web
pull redis-worker
up
```

This should lead to recreation of the containers "web" and "redis-worker", but "database" and "cache" should remain as they are. Abort `docker-compose up` after it initialized correctly, then start the containers in the background with `docker-compose start`.
Migrate the database:
```
docker-compose exec web php artisan migrate
```

Open the web interface, click the edit button for one device of your choice. Click on save on this page, without necessarily making changes. (This will lead to same background processes being triggered).

**Comment by Merphun** [comment]
Hi,
thanks for pointing me into the right direction. The Update worked this way smooth and witout problems on synology. Just two additions (if youm plan to update your manual with this):

- First you have to Navigate to the directory where gbroker has been installed ;-)
- Second on synology it was necessary to run the docker-compose commands as sudo

I'll test the new functionality asap, thanks!
Mike

**Comment by peterkappelt** [comment]
Thanks for testing, I'm going to add these points to the docs.
Please re-open the issue or comment if there are any further questions.
